# remap prefix to Control + a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# set terminal colors
set -as terminal-overrides ",xterm-256color:RGB"

# force a reload of the config file
unbind r
bind r source-file "$XDG_CONFIG_HOME/tmux/tmux.conf"

# quick pane cycling
unbind ^A
bind ^A select-pane -t :.+

# send prefix to current window
set-option -g prefix C-a
bind-key v send-prefix

set -g base-index 1
set-option -g renumber-windows on

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'
set-option -g set-titles on

set -g status-keys vi
set -g history-limit 30000
set -g focus-events on

setw -g mode-keys vi
setw -g mouse on
setw -g monitor-activity on

# make new panes and windows use the pwd
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# No delay for escape key press
set -sg escape-time 0

# URL support
set -as terminal-features 'xterm*:hyperlinks'

# List of plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$XDG_CONFIG_HOME/tmux/plugins/"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# for integrated navigation between nvim splits and tmux panes
set -g @plugin 'jabirali/tmux-tilish'
set -g @tilish-smartsplits 'on' # for smart-splits.nvim

# for neovim session resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-dir "$XDG_CACHE_HOME/tmux/resurrect"

# for tmux session persistence across restarts
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'iterm,fullscreen' # TODO?
set -g @continuum-restore 'on'

# Source statusline + pane visual styling
source-file "$XDG_CONFIG_HOME/tmux/statusline.conf"

# Initialize tmux plugin manager (must be last line)
run -b "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
