# fresh configuration
source ~/.fresh/build/shell.sh
export FRESH_LOCAL="$HOME/dotfiles"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# vi bindings
bindkey -v
# fix inability to backspace after swapping to normal mode (weird gremlin)
bindkey "^?" backward-delete-char

# aws-vault configuration https://github.com/99designs/aws-vault/blob/master/USAGE.md
export AWS_VAULT_KEYCHAIN_NAME="login" # use the macos one for less prompts

# aws regional endpoints
export AWS_STS_REGIONAL_ENDPOINTS=regional

# Go development
export GOPATH="${HOME}/go"
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# Ruby development
#eval "$(rbenv init -)"
export BUNDLER_EDITOR="nvim"

# gnu utils
PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
DEFAULT_USER="$USER"

# configure Starship prompt
eval "$(starship init zsh)"
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

bindkey "^U" backward-kill-line

# add redo
bindkey "^X^_" redo

# macros
gup='git fetch --prune && git rebase --autostash FETCH_HEAD'
gd='git l'

# used for autocomplete wd
gh() {
	if [ ! -d ~/github/$1 ]; then
		cd ~/github
		if git ls-remote "git@github.com:buildkite/$1.git" -q; then
			git clone "git@github.com:buildkite/$1.git"
		elif git ls-remote "git@github.com:chloeruka/$1.git" -q; then
			git clone "git@github.com:chloeruka/$1.git"
		else
			echo "Unable to find repository \"$1\" in either github.com/buildkite OR github.com/chloeruka"
		fi
	fi
	cd ~/github/$1
}
compctl -W ~/github/ -/ gh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_TMUX=1
export FZF_TMUX=20%
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

# Load Git completion
#zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
autoload -Uz compinit && compinit

# better file/dir completion (source: https://stackoverflow.com/a/24237590)
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
fpath=(~/.zsh $fpath)

