# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# fresh configuration
source ~/.fresh/build/shell.sh
export FRESH_LOCAL="$HOME/dotfiles"

# Path to your oh-my-zsh installation.
#export ZSH="/Users/chloe.hutchinson/.oh-my-zsh"
#export GITSTATUS_DIR="$ZSH/custom/plugins/gitstatus"
#source "$GITSTATUS_DIR/gitstatus.plugin.zsh"

# vi bindings
bindkey -v
# fix inability to backspace after swapping to normal mode (weird gremlin)
bindkey "^?" backward-delete-char

# Go development
export GOPATH="${HOME}/go"
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# Ruby development
eval "$(rbenv init -)"
export BUNDLER_EDITOR="nvim"

# gnu utils
PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
DEFAULT_USER="$USER"

# configure Starship prompt
eval "$(starship init zsh)"
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
#
# Change hexcodes for iterm bindings
# change hex 0x15 to delete everything to the left of the cursor rather than the whole line:
bindkey "^U" backward-kill-line

# add redo
bindkey "^X^_" redo

# startup commands
#tmux


# Set Spaceship ZSH as a prompt
#autoload -U promptinit; promptinit
#prompt spaceship

# macros
gup='git fetch --prune && git rebase --autostash FETCH_HEAD'
gd='git l'

# used for autocomplete wd
gh() { cd ~/github/$1; }
compctl -W ~/github/ -/ gh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_TMUX=1
export FZF_TMUX=20%
export FZF_DEFAULT_COMMAND='fd --type f --exclude .git'

# Load Git completion
#zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
autoload -Uz compinit && compinit

# better file/dir completion (source: https://stackoverflow.com/a/24237590)
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
fpath=(~/.zsh $fpath)

